apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmefit-frontend
  namespace: acme-fitness
  labels:
    finops.org/application: acme-fitness
    finops.org/cost-center: acme-1001
    finops.org/team: road-runner